name: ci

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest

      - name: hello
        run : echo 'Hello'
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
              cd ~/projets/demo1/leon/myhello_actions
              pwd
              git pull origin master
              git status
              npm install
              docker container stop leoringot62
              docker container rm leoringot62
              DOCKER_BUILDKIT=1 docker build -t clockbox .
              docker run -dp 3005:3005 --name="leoringot62" clockbox
              docker ps -a

      # - name: pull
      #   uses: actions/checkout@v3 #aller récupérer un repo
      #   with: